site_name: Isshiki修's Notebook
site_author: Isshiki修
site_url: 'https://note.isshikih.top'

repo_name: 'IsshikiHugh/notebook'
repo_url: 'https://github.com/IsshikiHugh/notebook'
edit_uri: blob/main/docs

theme: 
  name: material
  language: zh
  icon: 
    logo: material/notebook-outline
  font:
    text: Share Tech
    code: JetBrains Mono
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
  custom_dir: overrides

plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - comming.md
        - link.md
        - tech_accu/index.md
        - cour_note/index.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math

copyright: 'Copyright &copy 2022 Isshiki修'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IsshikiHugh
      name: Github

extra_css:
  - _css/extra.css

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - _js/extra.js




nav:
  - 💠 封面: 
    - 💠 封面: index.md
    - 💬 交流区: link.md
  - 📚 技术积累:
    - tech_accu/index.md
    - 常用工具:
      - Git Something:
        - tech_accu/tool/Git/Workflow/main.md
        - tech_accu/tool/Git/Commands/main.md
      - tech_accu/tool/Shell/main.md
      - tech_accu/tool/Colab/main.md
    - 标准 | 格式 | 规范:
      - tech_accu/standard/BVH_format/main.md
  - 🗒 课程笔记:
    - cour_note/index.md
    - cour_note/D1QD_CXiaoCheng/main.md
    - cour_note/D2QD_Intro2CV/main.md
  - 📝 实践记录:
    - comming.md 
  - 🚧 施工中:
    - comming.md
